### ISSUE TITLE
Discussion: User account management

### ISSUE THREAD

**Issue by seppeljordan** [ida-arbeitszeit/workers-control#851]
It is planned to implement certain features for users to manage their user accounts in the application. This includes the following features:

- #728 
- #658 
- #372

It is currently not clear how those features are integrated into the page hierarchy of the webserver. At the time of writing this we segregate all of our routes into 5 different [flask blueprints](https://flask.palletsprojects.com/en/latest/tutorial/views/) `member`, `company`, `accountant`, `auth` and `plots`. I can see two options on how to integrate those planned features into that structure:

# Create user account management blueprint

We would create a new blueprint called `user` or something similar. This blueprint would contain all the functionality described in the above issues and possibly more. The idea would be that it contained all the user account management functionality that should be shared among all the different user account types (member, company and accountant). The advantages of this would be that we only needed to implement all the web logic once and also that users could access their account settings in the same way no matter if they are currently logged in as an accountant, member or company. 

The disadvantage of this approach is that it would be hard and/or complicated to implement "exceptions" for certain roles. Let's say that for some reason the accountant user type would not be allowed to do certain things with their account compared to users that are non accountants. It would be awkward to implement such an exception in a general blueprint that is supposed to serve all different kinds of user accounts.

# Implement the user account management under each of the 3 user account blueprints `member`, `company` and `accountant`

This would have the advantage that we could easily customize the web interface depending on the users role. This advantage would be diminished somewhat by the fact that a user that is currently logged in as a member would need to experience the same rules for account management as an account would provided that their user account is also registered as an accountant.

The disadvantage is that we would need to repeat the code for this kind of stuff 3 times. Although this repetition would probably be minimal since we would reuse the business logic as much as possible anyway. Another disadvantage would be that the user account handling might look differently to the user depending on the role they are currently logged in as.

# Bonus: Integrate the account management logic under `auth`

I would like to discard this approach since the only advantage of this approach is that we would not need to create a separate blueprint while it would share all of the disadvantages of creating a new blueprint in addition to being confusing to the reader since the planned features are not really centered around authentication.

 # My opinion on the matter

I personally favor the first option where we would create a separate blueprint for user management.

**Comment by Amittai-Aviram** [comment]
I support the first approach as well.  I think we could perhaps solve the implementation problems related to customizing behavior according to role through a level of indirection.  We could keep a DB table or data structure that describes access permissions and presenter behavior.  When you log in with a certain role, the role determines which of those parameters is available for a query.  For instance, we maintain a dictionary from role to a bunch of such access and presenter settings.  A global object holds those settings, so any function elsewhere in the codebase can query that obect as it would a DB table to find out whether, e.g., the user is allowed to view or change some item of data.
