### ISSUE TITLE
RFC: Move authorization logic to business logic layer

### ISSUE THREAD

**Issue by seppeljordan** [ida-arbeitszeit/workers-control#919]
EDIT: After realizing that not everybody might be familiar with the difference between authorization and authentication I decided to preface the original post by a short explanation.

*Authentication: Who are you? Authorization: Are you allowed to do that?*

Currently our authorization logic is mostly (but not completely) implemented in the outer most layer of our code base located under `arbeitszeit_flask`. This is/was feasible since our authorization model until now was pretty easy to follow:

* Actions and queries are authorized on a user role basis
* Users with unconfirmed email addresses cannot do anything role specific
* Some specific queries are available to all roles with or without confirmation of their email address

I propose that we move all of our authorization logic from the outer most layer to the inner most layer in our code, e.g. the business logic layer located under `arbeitszeit`.

The decision whether an action is available to the user is largely based on business logic considerations. For example 

* trying to pass the coordination role of a cooperation is only allowed for the current coordinator of a cooperation
* submitting a plan is only allowed for the planner
* registering hours worked is only allowed for the companies where a worker is already registered as a member

Those considerations are also independent of the current (http) session. Checking of the email address of a user is confirmed requires checking the database. This means that we incur at least one additional database lookup per request just to see if the users email address is confirmed.

When continuing the development of our JSON API we would also need to have the same authorization logic in place as the web interface. To me this is a strong indicator that the authorization logic should go into common layer that is shared between individual delivery methods.

Before going further with this I would like to know what you think about this approach. If we decide that we want to move into this direction then we could develop a concrete plan on how to proceed.

/cc @sloschert @Amittai-Aviram

**Comment by sloschert** [comment]
I also think we should move authorization logic to the business layer wherever it makes sense.
But I think we should first make our app "feature complete" (the absolute necessary features), before we invest much time into this project.

**Comment by sloschert** [comment]
Do I understand you correctly that you are proposing to refactor the existing code to comply with the proposel?

If that's the case, my reasoning is: 
1) We agreed on aiming to be "feature complete" better sooner than later. At least I was under the impression that we agreed on this.
2) I think there are actually not so many features to implement before we are "feature complete", so the additional work if we refactor later will not increase so much
3) I expect the change you are proposing (if you propose to refactor the existing code) to be quite time consuming

**Comment by sloschert** [comment]
I find it hard to estimate. I think the majority of use cases would be eligible for refactoring? This would also affect controllers. And tests of course. 

Random guess: 3 - 4 months of work (if we work as much as we did in the last months and if we concentrate on this task)?
